---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: deploy NSX Manager OVA
      nsxt_deploy_ova:
        vcenter: "{{hostvars['localhost'].vcenter_ip}}"
        vcenter_user: "{{hostvars['localhost'].vcenter_username}}"
        vcenter_passwd: "{{hostvars['localhost'].vcenter_password}}"
        datacenter: "{{hostvars['localhost'].vcenter_datacenter}}"
        datastore: "{{hostvars['localhost'].vcenter_datastore}}"
        portgroup: "{{hostvars['localhost'].mgmt_portgroup}}"
        cluster: "{{hostvars['localhost'].vcenter_cluster}}"
        vmname: "nsxt-manager"
        hostname: "{{hostvars['localhost'].nsx_manager_assigned_hostname}}"
        dns_server: "{{hostvars['localhost'].dns_server}}"
        dns_domain: "{{hostvars['localhost'].dns_domain}}"
        ntp_server: "{{hostvars['localhost'].ntp_servers}}"
        gateway: "{{hostvars['localhost'].default_gateway}}"
        ip_address: "{{hostvars['localhost'].nsx_manager_ip}}"
        netmask: "{{hostvars['localhost'].netmask}}"
        admin_password: "{{hostvars['localhost'].nsx_manager_password}}"
        cli_password: "{{hostvars['localhost'].nsx_manager_password}}"
        ovftool_path: "{{ovftool_bin_path}}"
        path_to_ova: "{{hostvars['localhost'].nsx_image_webserver}}"
        ova_file: "{{hostvars['localhost'].ova_file_name}}"
        deployment_size: "{{hostvars['localhost'].nsx_manager_deployment_size}}"
        role: "nsx-manager"

    - name: Check manager status
      nsxt_manager_status:
        hostname: "{{hostvars['localhost'].nsx_manager_ip}}"
        username: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        validate_certs: False
        wait_time: 50

    # this should've been enabled already
    - name: Enable install-upgrade service
      uri:
        method: PUT
        url: https://{{hostvars['localhost'].nsx_manager_ip}}/api/v1/node/services/install-upgrade
        user: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        body:
          service_name: "install-upgrade"
          service_properties:
            enabled: True
        body_format: json
        force_basic_auth: yes
        validate_certs: no

    - name: Restart install-upgrade service
      uri:
        method: POST
        url: https://{{hostvars['localhost'].nsx_manager_ip}}/api/v1/node/services/install-upgrade?action=restart
        user: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        force_basic_auth: yes
        validate_certs: no

    - name: Deploy compute manager
      nsxt_fabric_compute_managers:
        hostname: "{{hostvars['localhost'].nsx_manager_ip}}"
        username: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        validate_certs: False
        display_name: "vCenter-compute-manager"
        server: "{{hostvars['localhost'].vcenter_ip}}" # vCenter IP
        origin_type: vCenter
        credential:
          credential_type: UsernamePasswordLoginCredential
          username: "{{hostvars['localhost'].compute_manager_username}}"
          password: "{{hostvars['localhost'].compute_manager_password}}"
        state: present
      register: compute_manager

# TODO: Not idempotent
    - name: Deploy controller
      nsxt_controllers:
        hostname: "{{hostvars['localhost'].nsx_manager_ip}}"
        username: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        validate_certs: False
        deployment_requests:
        - roles:
          - CONTROLLER
          form_factor: "{{hostvars[item].controller_deployment_size}}"
          user_settings:
            cli_password: "{{hostvars[item].controller_cli_password}}"
            root_password: "{{hostvars[item].controller_root_password}}"
          deployment_config:
            placement_type: VsphereClusterNodeVMDeploymentConfig
            vc_id: "{{compute_manager.id}}"
            management_network_id: "{{hostvars[item].vc_management_network_for_controller}}"
            hostname: "{{hostvars[item].hostname}}"
            compute_id: "{{hostvars[item].vc_cluster_for_controller}}"
            storage_id: "{{hostvars[item].vc_datastore_for_controller}}" # https://10.40.1.206/mob/?moid=datacenter-20.
            default_gateway_addresses:
            - "{{hostvars[item].default_gateway}}"
            management_port_subnets:
            - ip_addresses:
              - "{{hostvars[item].ip}}"
              prefix_length: "{{hostvars[item].prefix_length}}"
        clustering_config:
          clustering_type: ControlClusteringConfig
          shared_secret: "{{hostvars[item].controller_shared_secret}}"
          join_to_existing_cluster: false
        state: present
      with_items: "{{groups['controllers']}}"

    - name: Add Edge VM
      nsxt_fabric_nodes:
        hostname: "{{hostvars['localhost'].nsx_manager_ip}}"
        username: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        validate_certs: False
        resource_type: "EdgeNode"
        display_name: "{{hostvars[item].edge_fabric_node_name}}"
        ip_addresses:
          - "{{hostvars[item].ip}}"
        deployment_config:
          form_factor: "{{hostvars[item].edge_deployment_size}}"
          node_user_settings:
            cli_password: "{{hostvars[item].edge_cli_password}}"
            root_password: "{{hostvars[item].edge_root_password}}"
          vm_deployment_config:
            placement_type: VsphereDeploymentConfig
            vc_id: "{{compute_manager.id}}"
            data_network_ids:
            - "{{hostvars[item].vc_uplink_network_for_edge}}"
            - "{{hostvars[item].vc_overlay_network_for_edge}}"
            - "{{hostvars[item].vc_management_network_for_edge}}"
            management_network_id: "{{hostvars[item].vc_management_network_for_edge}}"
            hostname: "{{hostvars[item].hostname}}"
            compute_id: "{{hostvars[item].vc_cluster_for_edge}}"
            storage_id: "{{hostvars[item].vc_datastore_for_edge}}"
            default_gateway_addresses:
            - "{{hostvars[item].default_gateway}}"
            management_port_subnets:
            - ip_addresses:
              - "{{hostvars[item].ip}}"
              prefix_length: "{{hostvars[item].prefix_length}}"
        state: "present"
      with_items: "{{groups['edge_nodes']}}"
